import { CelebrationCategory } from '../celebrations/celebrationDefinitions';
import { Locale } from '../../locale';

export type ExpansionDatasetId = 'sv-SE' | 'en-US';

type FixedDateRule = {
  dateType: 'fixed';
  monthIndex: number;
  dayOfMonth: number;
};

type NthWeekdayRule = {
  dateType: 'nth-weekday';
  monthIndex: number;
  weekday: number;
  occurrence: number;
};

type InternationalCelebrationRule = {
  dayType: string;
  category: CelebrationCategory;
  score: number;
  rule: FixedDateRule | NthWeekdayRule;
  copy: Record<
    Locale,
    {
      title: string;
      subtitle: string;
      kicker: string;
    }
  >;
};

export type InternationalCelebrationDataset = {
  id: ExpansionDatasetId;
  label: string;
  defaultLocale: Locale;
  calendarName: string;
  calendarDescription: string;
  rules: InternationalCelebrationRule[];
};

function getNthWeekdayOfMonth(
  year: number,
  monthIndex: number,
  weekday: number,
  occurrence: number
): Date {
  const firstDay = new Date(year, monthIndex, 1);
  const firstOffset = (weekday - firstDay.getDay() + 7) % 7;
  const dayOfMonth = 1 + firstOffset + (occurrence - 1) * 7;
  return new Date(year, monthIndex, dayOfMonth);
}

export function getInternationalCelebrationDatasets(): InternationalCelebrationDataset[] {
  return [
    {
      id: 'en-US',
      label: 'United States',
      defaultLocale: 'en',
      calendarName: 'Vad kan man fira? (US)',
      calendarDescription: 'A lightweight US celebration calendar generated by Vad kan man fira?',
      rules: [
        {
          dayType: 'valentines-day',
          category: 'observance',
          score: 74,
          rule: {
            dateType: 'fixed',
            monthIndex: 1,
            dayOfMonth: 14,
          },
          copy: {
            sv: {
              title: 'Valentine’s Day',
              subtitle: 'Amerikansk romantik med butikskvitton.',
              kicker: 'Hjärtformad plikt',
            },
            en: {
              title: "Valentine's Day",
              subtitle: 'Cards, sugar, and coordinated sincerity.',
              kicker: 'Heart-shaped obligation',
            },
            'pt-BR': {
              title: "Valentine's Day",
              subtitle: 'Cartões, açúcar e sinceridade coordenada.',
              kicker: 'Obrigação em forma de coração',
            },
          },
        },
        {
          dayType: 'independence-day',
          category: 'official',
          score: 90,
          rule: {
            dateType: 'fixed',
            monthIndex: 6,
            dayOfMonth: 4,
          },
          copy: {
            sv: {
              title: 'Independence Day',
              subtitle: 'Flaggor, fyrverkerier och nationell självkänsla.',
              kicker: 'Rödvitblå tyngd',
            },
            en: {
              title: 'Independence Day',
              subtitle: 'Flags, fireworks, and national self-confidence.',
              kicker: 'Red white and blue gravity',
            },
            'pt-BR': {
              title: 'Independence Day',
              subtitle: 'Bandeiras, fogos e autoconfiança nacional.',
              kicker: 'Peso vermelho branco e azul',
            },
          },
        },
        {
          dayType: 'labor-day',
          category: 'official',
          score: 68,
          rule: {
            dateType: 'nth-weekday',
            monthIndex: 8,
            weekday: 1,
            occurrence: 1,
          },
          copy: {
            sv: {
              title: 'Labor Day',
              subtitle: 'Sommarens sista djupa andetag.',
              kicker: 'Ledig måndag',
            },
            en: {
              title: 'Labor Day',
              subtitle: 'The long weekend that politely ends summer.',
              kicker: 'Public Monday relief',
            },
            'pt-BR': {
              title: 'Labor Day',
              subtitle: 'O feriado prolongado que encerra o verão com educação.',
              kicker: 'Alívio de segunda-feira',
            },
          },
        },
        {
          dayType: 'halloween',
          category: 'seasonal',
          score: 82,
          rule: {
            dateType: 'fixed',
            monthIndex: 9,
            dayOfMonth: 31,
          },
          copy: {
            sv: {
              title: 'Halloween',
              subtitle: 'Pumpor, socker och socialt sanktionerad märklighet.',
              kicker: 'Kostymerad energi',
            },
            en: {
              title: 'Halloween',
              subtitle: 'Candy, costumes, and approved seasonal nonsense.',
              kicker: 'Costumed momentum',
            },
            'pt-BR': {
              title: 'Halloween',
              subtitle: 'Doces, fantasias e caos sazonal autorizado.',
              kicker: 'Energia fantasiada',
            },
          },
        },
        {
          dayType: 'thanksgiving',
          category: 'official',
          score: 88,
          rule: {
            dateType: 'nth-weekday',
            monthIndex: 10,
            weekday: 4,
            occurrence: 4,
          },
          copy: {
            sv: {
              title: 'Thanksgiving',
              subtitle: 'Kalkon, logistik och familjediplomati.',
              kicker: 'Tacksamhet under tryck',
            },
            en: {
              title: 'Thanksgiving',
              subtitle: 'Turkey, logistics, and family diplomacy.',
              kicker: 'Gratitude under pressure',
            },
            'pt-BR': {
              title: 'Thanksgiving',
              subtitle: 'Peru, logística e diplomacia familiar.',
              kicker: 'Gratidão sob pressão',
            },
          },
        },
      ],
    },
  ];
}

export function getInternationalCelebrationDate(
  year: number,
  rule: InternationalCelebrationRule['rule']
): Date {
  if (rule.dateType === 'fixed') {
    return new Date(year, rule.monthIndex, rule.dayOfMonth);
  }

  return getNthWeekdayOfMonth(year, rule.monthIndex, rule.weekday, rule.occurrence);
}
